server:
  port: 8085
  servlet:
    session.timeout: 60000
    contextpath: /

spring:
  datasource:
    url: jdbc:mysql://47.98.255.160:3308/res?serverTimezone=UTC
    username: zhulin
    password: zhulin0804

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #开启sql语句打印