server:
  port: 8085
  servlet:
    tomcat:
      max-swallow-size: 100MB;
    multipart:
      max-file-size: 100MB;
      max-request-size: 100MB;
    session.timeout: 60000
    contextpath: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/res?serverTimezone=UTC
    username: root
    password: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #开启sql语句打印